module.exports = [
    null,
    "Unsupported protocol. This build of curl has no support for this protocol.",
    "Failed to initialize.",
    "URL malformed. The syntax was not correct.",
    null,
    "Couldn't resolve proxy. The given proxy host could not be resolved.",
    "Couldn't resolve host. The given remote host was not resolved.",
    "Failed to connect to host.",
    "FTP weird server reply. The server sent data curl couldn't parse.",
    "FTP access denied. The server denied login or denied access to the particular resource or directory you wanted to reach. Most often you tried to change to a directory that doesn't exist on the server.",
    null,
    "FTP weird PASS reply. Curl couldn't parse the reply sent to the PASS request.",
    null,
    "FTP weird PASV reply, Curl couldn't parse the reply sent to the PASV request.",
    "FTP weird 227 format. Curl couldn't parse the 227-line the server sent.",
    "FTP can't get host. Couldn't resolve the host IP we got in the 227-line.",
    null,
    "FTP couldn't set binary. Couldn't change transfer method to binary.",
    "Partial file. Only a part of the file was transferred.",
    "FTP couldn't download/access the given file, the RETR (or similar) command failed.",
    null,
    "FTP quote error. A quote command returned error from the server.",
    "HTTP page not retrieved. The requested url was not found or returned another error with the HTTP error code being 400 or above. This return code only appears if -f/--fail is used.",
    "Write error. Curl couldn't write data to a local filesystem or similar.",
    null,
    "FTP couldn't STOR file. The server denied the STOR operation, used for FTP uploading.",
    "Read error. Various reading problems.",
    "Out of memory. A memory allocation request failed.",
    "Operation timeout. The specified time-out period was reached according to the conditions.",
    null,
    "FTP PORT failed. The PORT command failed. Not all FTP servers support the PORT command, try doing a transfer using PASV instead!",
    "FTP couldn't use REST. The REST command failed. This command is used for resumed FTP transfers.",
    null,
    "HTTP range error. The range command didn't work.",
    "HTTP post error. Internal post-request generation error.",
    "SSL connect error. The SSL handshaking failed.",
    "FTP bad download resume. Couldn't continue an earlier aborted download.",
    "FILE couldn't read file. Failed to open the file. Permissions?",
    "LDAP cannot bind. LDAP bind operation failed.",
    "LDAP search failed.",
    null,
    "Function not found. A required LDAP function was not found.",
    "Aborted by callback. An application told curl to abort the operation.",
    "Internal error. A function was called with a bad parameter.",
    null,
    "Interface error. A specified outgoing interface could not be used.",
    null,
    "Too many redirects. When following redirects, curl hit the maximum amount.",
    "Unknown TELNET option specified.",
    "Malformed telnet option.",
    null,
    "The peer's SSL certificate or SSH MD5 fingerprint was not ok.",
    "The server didn't reply anything, which here is considered an error.",
    "SSL crypto engine not found.",
    "Cannot set SSL crypto engine as default.",
    "Failed sending network data.",
    "Failure in receiving network data.",
    null,
    "Problem with the local certificate.",
    "Couldn't use specified SSL cipher.",
    "Peer certificate cannot be authenticated with known CA certificates.",
    "Unrecognized transfer encoding.",
    "Invalid LDAP URL.",
    "Maximum file size exceeded.",
    "Requested FTP SSL level failed.",
    "Sending the data requires a rewind that failed.",
    "Failed to initialise SSL Engine.",
    "The user name, password, or similar was not accepted and curl failed to log in.",
    "File not found on TFTP server.",
    "Permission problem on TFTP server.",
    "Out of disk space on TFTP server.",
    "Illegal TFTP operation.",
    "Unknown TFTP transfer ID.",
    "File already exists (TFTP).",
    "No such user (TFTP).",
    "Character conversion failed.",
    "Character conversion functions required.",
    "Problem with reading the SSL CA cert (path access rights).",
    "The resource referenced in the URL does not exist.",
    "An unspecified error occurred during the SSH session.",
    "Failed to shut down the SSL connection.",
    null,
    "Could not load CRL file, missing or wrong format.",
    "Issuer check failed."
];

